import type { Category, Idea, IdeaStatus } from "@/types/idea";

export const MOCK_CATEGORIES: Category[] = [
  { id: "1", label: "UI / UX", slug: "ui-ux", color: "#2563eb" },
  { id: "2", label: "Performance", slug: "performance", color: "#0f766e" },
  { id: "3", label: "Integrations", slug: "integrations", color: "#9333ea" },
  { id: "4", label: "Mobile", slug: "mobile", color: "#ea580c" },
  { id: "5", label: "API", slug: "api", color: "#475569" },
  { id: "6", label: "Security", slug: "security", color: "#b91c1c" },
];

const minutesAgo = (minutes: number) => new Date(Date.now() - minutes * 60_000).toISOString();
const daysAgo = (days: number) => new Date(Date.now() - days * 86_400_000).toISOString();

const categoryBySlug = Object.fromEntries(MOCK_CATEGORIES.map((category) => [category.slug, category]));

const makeIdea = ({
  id,
  title,
  description,
  status,
  voteCount,
  commentCount,
  hasVoted = false,
  categories,
  authorId,
  authorName,
  createdAt,
  updatedAt,
}: {
  id: string;
  title: string;
  description: string;
  status: IdeaStatus;
  voteCount: number;
  commentCount: number;
  hasVoted?: boolean;
  categories: Array<keyof typeof categoryBySlug>;
  authorId: string;
  authorName: string;
  createdAt: string;
  updatedAt: string;
}): Idea => ({
  id,
  title,
  description,
  excerpt: description.length > 120 ? `${description.slice(0, 117)}...` : description,
  status,
  voteCount,
  commentCount,
  hasVoted,
  categories: categories.map((category) => categoryBySlug[category]),
  authorId,
  authorName,
  createdAt,
  updatedAt,
});

export const MOCK_IDEAS: Idea[] = [
  makeIdea({
    id: "1",
    title: "Add dark mode support",
    description: "Late-night support teams need a calmer interface that reduces glare across dashboards, feedback triage, and idea review.",
    status: "planned",
    voteCount: 128,
    commentCount: 14,
    categories: ["ui-ux"],
    authorId: "u1",
    authorName: "Sarah M.",
    createdAt: daysAgo(18),
    updatedAt: daysAgo(2),
  }),
  makeIdea({
    id: "2",
    title: "CSV export for reports",
    description: "Teams want to export filtered report views into CSV so they can share weekly digests with finance and operations.",
    status: "shipped",
    voteCount: 94,
    commentCount: 6,
    categories: ["api", "performance"],
    authorId: "u2",
    authorName: "Jordan K.",
    createdAt: daysAgo(24),
    updatedAt: daysAgo(1),
  }),
  makeIdea({
    id: "3",
    title: "Slack integration for comment alerts",
    description: "Route idea updates and comment mentions into Slack channels so product squads can respond without opening the app constantly.",
    status: "in_progress",
    voteCount: 76,
    commentCount: 22,
    categories: ["integrations"],
    authorId: "u3",
    authorName: "Amina P.",
    createdAt: daysAgo(10),
    updatedAt: minutesAgo(90),
  }),
  makeIdea({
    id: "4",
    title: "Custom webhook support",
    description: "Enterprise customers need outbound webhooks whenever idea status changes so they can sync roadmap updates into internal tools.",
    status: "under_review",
    voteCount: 55,
    commentCount: 8,
    categories: ["api", "integrations"],
    authorId: "u4",
    authorName: "Chris T.",
    createdAt: daysAgo(6),
    updatedAt: daysAgo(1),
  }),
  makeIdea({
    id: "5",
    title: "Two-factor authentication",
    description: "Admins need stronger account protection for customer feedback workspaces that include sensitive roadmap planning.",
    status: "planned",
    voteCount: 43,
    commentCount: 3,
    categories: ["security"],
    authorId: "u5",
    authorName: "Mina R.",
    createdAt: daysAgo(30),
    updatedAt: daysAgo(5),
  }),
  makeIdea({
    id: "6",
    title: "Bulk tag ideas",
    description: "Support teams want to tag similar ideas in bulk after importing feedback from calls and tickets.",
    status: "declined",
    voteCount: 12,
    commentCount: 1,
    categories: ["ui-ux"],
    authorId: "u6",
    authorName: "Leo D.",
    createdAt: daysAgo(40),
    updatedAt: daysAgo(25),
  }),
  makeIdea({
    id: "7",
    title: "Offline-friendly mobile review mode",
    description: "Mobile PMs need to read and queue feedback decisions while traveling with poor connectivity.",
    status: "under_review",
    voteCount: 67,
    commentCount: 11,
    categories: ["mobile", "performance"],
    authorId: "u7",
    authorName: "Priya S.",
    createdAt: daysAgo(4),
    updatedAt: minutesAgo(30),
  }),
  makeIdea({
    id: "8",
    title: "SAML single sign-on",
    description: "Security teams want SAML support so employees can access the feedback portal through existing identity providers.",
    status: "planned",
    voteCount: 81,
    commentCount: 10,
    categories: ["security", "integrations"],
    authorId: "u8",
    authorName: "Noah B.",
    createdAt: daysAgo(12),
    updatedAt: daysAgo(3),
  }),
  makeIdea({
    id: "9",
    title: "Saved filter views for triage teams",
    description: "Product ops needs reusable combinations of status, category, and sort settings to speed up weekly triage sessions.",
    status: "in_progress",
    voteCount: 51,
    commentCount: 9,
    categories: ["ui-ux", "performance"],
    authorId: "u9",
    authorName: "Elena V.",
    createdAt: daysAgo(8),
    updatedAt: daysAgo(2),
  }),
  makeIdea({
    id: "10",
    title: "Public idea sharing link",
    description: "Customer-facing teams want a read-only share link they can send to clients when confirming roadmap direction.",
    status: "planned",
    voteCount: 39,
    commentCount: 5,
    categories: ["api", "ui-ux"],
    authorId: "u10",
    authorName: "Daniel C.",
    createdAt: daysAgo(15),
    updatedAt: daysAgo(7),
  }),
  makeIdea({
    id: "11",
    title: "Faster board loading for large workspaces",
    description: "Boards with thousands of ideas should load faster with lighter payloads and deferred metadata.",
    status: "shipped",
    voteCount: 58,
    commentCount: 13,
    categories: ["performance"],
    authorId: "u11",
    authorName: "Tara G.",
    createdAt: daysAgo(20),
    updatedAt: minutesAgo(300),
  }),
  makeIdea({
    id: "12",
    title: "Dark theme for mobile app",
    description: "Users have requested a dedicated dark theme on mobile so feedback review feels consistent across platforms.",
    status: "under_review",
    voteCount: 44,
    commentCount: 4,
    categories: ["mobile", "ui-ux"],
    authorId: "u12",
    authorName: "Owen L.",
    createdAt: daysAgo(9),
    updatedAt: daysAgo(4),
  }),
];
